name: security

concurrency:
  group: security-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  govulncheck:
    runs-on: ubuntu-slim
    permissions:
      contents: read # same as global permissions
      security-events: write # required to write sarif report
      actions: read # required to upload sarif report
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - name: Run govulncheck
        run: go run golang.org/x/vuln/cmd/govulncheck@v1.7.0 -format sarif ./... > govulncheck.sarif
        continue-on-error: true
      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@ff2f1c621b7f889edc0d3c761ac2e6a3f8cdb0dd # v4.37.7
        with:
          sarif_file: govulncheck.sarif

  coverage:
    runs-on: ubuntu-slim
    permissions:
      contents: read # same as global permissions
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - name: Compute coverage
        run: go test ./... -coverprofile=coverage.out
      - name: Upload coverage
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false